"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['flasher/Flasher.py']
DATA_FILES = ['flasher/logo.gif']
OPTIONS = {
    'argv_emulation': True,
    'iconfile':'flasher/icon.icns',
}

setup(
    name="XAOC Firmware Update Tool",
    version="0.1",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
